### PR TITLE
Fix download link top right

### PR DESCRIPTION
**Pull request by matthaias**
Hi,

the download link in the top didn't work. I hope this fix is correct. Also i removed the `target=_blank` since it opened a new emtpy tab.

### CODE REVIEW

**Comment by sallar** [comment]
Hi @matthaias, thanks for this. The header links are moved to their own component, could you update the PR please? :) Thanks!

**Comment by matthaias** [comment]
I updated my PR. It is now only on the download section since the button in the header makes sense for a small screen (i had a bigger one where i was opening this PR and after clicking nothing happend). Maybe it would be good to change the link href depending on the screen size?

**Comment by sallar** [comment]
@matthaias that makes sense. thanks. I'll merge this now though :)

**Review by sallar — APPROVED** [review]

**Comment by sallar** [comment]
I also want to spin up automatic deployment for this.

**Comment by matthaias** [comment]
> I also want to spin up automatic deployment for this.

Good idea. 

Thanks for merging this little change :)

**Pull request merged**
